### ISSUE TITLE
There is a problem with the use of the getOrders parameter

### ISSUE THREAD

**Issue by jiwei3187553** [clousale/amazon-sp-api-php#26]
I am using the getOrders interface, only the start time and end time are requested properly and return data, but using the order_statuses parameter will report an error, can anyone tell me why?

  $result = $apiInstance->getOrders($marketplace_id,'2021-01-31T03:23:29Z','2021-02-02T03:23:29Z', null,null,'Shipped');

![image](https://user-images.githubusercontent.com/25273864/107018854-edcbfe80-67db-11eb-9904-59a6121fc79a.png)

**Comment by piotr-lottestyle** [comment]
there is an error in this file

https://github.com/clousale/amazon-sp-api-php/blob/master/lib/Signature.php

As per docs https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html query string parameters should be sorted

> To construct the canonical query string, complete the following steps:

> Sort the parameter names by character code point in ascending order.

There will be other problems with that class. I suggested using class created by Amazon https://github.com/clousale/amazon-sp-api-php/issues/21 because AWS Signature it's not so trivial task
